[package]
name = "midos-house"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[build-dependencies]
git2 = "0.17"
thiserror = "1"

[dependencies]
anyhow = "1"
async-graphql = "5"
async-graphql-rocket = "5"
async-trait = "0.1"
base64 = "0.21"
chrono-tz = "0.8"
collect-mac = "0.1"
convert_case = "0.6"
csv = "1"
enum-iterator = "1"
futures = "0.3"
git2 = "0.17"
#graphql_client = "0.11" # workaround for https://github.com/smashgg/developer-portal/issues/171 — see also https://github.com/graphql-rust/graphql-client/pull/437
if_chain = "1"
ics = "0.5"
itertools = "0.10"
kuchiki = "0.8"
lazy-regex = "2"
once_cell = "1"
racetime = "0.17"
rand = "0.8"
rocket = "0.5.0-rc.3"
rocket_oauth2 = "0.5.0-rc.1"
serde_json = "1"
serde_plain = "1"
#sheets = "0.6" # can't upgrade to this due to https://github.com/oxidecomputer/third-party-api-clients/issues/72
thiserror = "1"
typemap_rev = "0.3"
uuid = "1"
yup-oauth2 = "5" # dependency of `sheets`

[dependencies.chrono]
version = "0.4"
#TODO disable default features once dependencies no longer use them (currently used e.g. by `sheets`)
features = ["serde"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.graphql_client]
git = "https://github.com/fenhl/graphql-client"
branch = "skip-default-scalars"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]

[dependencies.ootr-utils]
git = "https://github.com/midoshouse/rust-ootr-utils"
branch = "main"
features = ["sqlx"]

[dependencies.openssl]
version = "0.10"
features = ["vendored"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "trust-dns"]

[dependencies.rocket_csrf]
git = "https://github.com/fenhl/rocket_csrf"
branch = "impl-error"

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "main"
features = ["ics", "image", "rocket_csrf"]

[dependencies.semver]
version = "1"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_with]
version = "2"
features = ["json"]

[dependencies.serenity]
#version = "0.11"
git = "https://github.com/serenity-rs/serenity" # waiting for https://github.com/serenity-rs/serenity/pull/2357 to be published
branch = "next"
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils"
#branch = "main"
branch = "next" # waiting for https://github.com/serenity-rs/serenity/pull/2357 to be published

[dependencies.sheets]
git = "https://github.com/fenhl/cio"
branch = "tokio1"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["chrono", "json", "macros", "postgres", "runtime-tokio-rustls", "uuid"]

[dependencies.tokio]
version = "1"
features = ["fs", "net", "process", "sync", "time"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["reqwest", "rocket-beta", "serde", "serde_json"]

[target.'cfg(unix)'.dependencies]
xdg = "2"

[target.'cfg(unix)'.dependencies.async-proto]
version = "0.16.5"
features = ["chrono", "serde_json", "uuid"]
