[package]
name = "midos-house"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.13"
chrono-tz = "0.6"
enum-iterator = "1"
futures = "0.3"
ics = "0.5"
itertools = "0.10"
lazy-regex = "2"
once_cell = "1"
rand = "0.8"
rocket = "0.5.0-rc.2"
rocket_oauth2 = "0.5.0-rc.1"
serde_json = "1"
serde_plain = "1"
thiserror = "1"
xdg = "2"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "trust-dns"]

[dependencies.rocket_csrf]
git = "https://github.com/fenhl/rocket_csrf"
branch = "impl-error"

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "main"
features = ["ics", "image", "rocket_csrf"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["model", "rustls_backend"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["chrono", "macros", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["fs", "process"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["rocket-beta"]
