[package]
name = "midos-house"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.13"
rand = "0.8"
rocket = "0.5.0-rc.1"
rocket_oauth2 = "0.5.0-rc.1"
serde_json = "1"
xdg = "2"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.horrorshow]
git = "https://github.com/fenhl/horrorshow-rs"
branch = "rocket"
features = ["rocket"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "trust-dns"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["macros", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["fs"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["rocket-beta"]
