[package]
name = "midos-house"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.13"
itertools = "0.10"
once_cell = "1"
rand = "0.8"
rocket = "0.5.0-rc.1"
rocket_oauth2 = "0.5.0-rc.1"
serde_json = "1"
thiserror = "1"
xdg = "2"

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.horrorshow]
git = "https://github.com/fenhl/horrorshow-rs"
branch = "rocket"
features = ["rocket"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "trust-dns"]

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "main"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["macros", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["fs"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["rocket-beta"]
