[package]
name = "midos-house"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[build-dependencies]
git2 = "0.15"
itertools = "0.10"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
chrono-tz = "0.6"
collect-mac = "0.1"
enum-iterator = "1"
futures = "0.3"
#graphql_client = "0.11" # workaround for https://github.com/smashgg/developer-portal/issues/171
ics = "0.5"
itertools = "0.10"
lazy-regex = "2"
once_cell = "1"
racetime = "0.9"
rand = "0.8"
rocket = "0.5.0-rc.2"
rocket_oauth2 = "0.5.0-rc.1"
serde_json = "1"
serde_plain = "1"
thiserror = "1"
typemap_rev = "0.2"
yup-oauth2 = "5" # dependency of `sheets`

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.graphql_client]
git = "https://github.com/fenhl/graphql-client"
branch = "skip-default-scalars"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "trust-dns"]

[dependencies.rocket_csrf]
git = "https://github.com/fenhl/rocket_csrf"
branch = "impl-error"

[dependencies.rocket-util]
git = "https://github.com/fenhl/rocket-util"
branch = "main"
features = ["ics", "image", "rocket_csrf"]

[dependencies.semver]
version = "1"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_with]
version = "2"
features = ["json"]

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["model", "rustls_backend"]

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils"
branch = "main"

[dependencies.sheets]
git = "https://github.com/fenhl/cio"
branch = "tokio1"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["chrono", "json", "macros", "postgres", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1"
features = ["fs", "process", "sync", "time"]

[dependencies.tokio-util]
version = "0.7"
features = ["io"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
features = ["reqwest", "rocket-beta", "serde", "serde_json"]

[target.'cfg(unix)'.dependencies]
xdg = "2"

[target.'cfg(windows)'.dependencies]
directories = "4"
