-- Register MMR; seeds use the existing seed_config and seed_data columns.
INSERT INTO games (name, display_name, description)
VALUES ('mmr', 'Majora''s Mask Randomizer', 'Majora''s Mask Randomizer tournaments and events')
ON CONFLICT (name) DO NOTHING;

INSERT INTO hash_icons (game_id, name, file_name, racetime_emoji)
SELECT games.id, icons.name, icons.file_name, icons.racetime_emoji
FROM games CROSS JOIN (VALUES
    ('ITEM_OCARINA', 'mmr/HashOcarina.png', 'HashOcarina'),
    ('ITEM_BOW', 'mmr/HashBow.png', 'HashBow'),
    ('ITEM_FIRE_ARROW', 'mmr/HashFireArrow.png', 'HashFireArrow'),
    ('ITEM_ICE_ARROW', 'mmr/HashIceArrow.png', 'HashIceArrow'),
    ('ITEM_LIGHT_ARROW', 'mmr/HashLightArrow.png', 'HashLightArrow'),
    ('ITEM_BOMB', 'mmr/HashBomb.png', 'HashBomb'),
    ('ITEM_BOMBCHU', 'mmr/HashBombchu.png', 'HashBombchu'),
    ('ITEM_DEKU_STICK', 'mmr/HashDekuStick.png', 'HashDekuStick'),
    ('ITEM_DEKU_NUT', 'mmr/HashDekuNut.png', 'HashDekuNut'),
    ('ITEM_MAGIC_BEAN', 'mmr/HashBean.png', 'HashBean'),
    ('ITEM_POWDER_KEG', 'mmr/HashPowderKeg.png', 'HashPowderKeg'),
    ('ITEM_PICTOGRAPH', 'mmr/HashPictograph.png', 'HashPictograph'),
    ('ITEM_LENS', 'mmr/HashLens.png', 'HashLens'),
    ('ITEM_HOOKSHOT', 'mmr/HashHookshot.png', 'HashHookshot'),
    ('ITEM_EMPTY_BOTTLE', 'mmr/HashEmptyBottle.png', 'HashEmptyBottle'),
    ('ITEM_DEKU_PRINCESS', 'mmr/HashDekuPrincess.png', 'HashDekuPrincess'),
    ('ITEM_BUGS', 'mmr/HashBugs.png', 'HashBugs'),
    ('ITEM_BIG_POE', 'mmr/HashBigPoe.png', 'HashBigPoe'),
    ('ITEM_HOT_WATER', 'mmr/HashHotWater.png', 'HashHotWater'),
    ('ITEM_ZORA_EGG', 'mmr/HashZoraEgg.png', 'HashZoraEgg'),
    ('ITEM_GOLD_DUST_BOTTLE', 'mmr/HashGoldDust.png', 'HashGoldDust'),
    ('ITEM_MUSHROOM', 'mmr/HashMushroom.png', 'HashMushroom'),
    ('ITEM_SEAHORSE', 'mmr/HashSeahorse.png', 'HashSeahorse'),
    ('ITEM_CHATEAU_ROMANI_BOTTLE', 'mmr/HashChateau.png', 'HashChateau'),
    ('ITEM_MOON_TEAR', 'mmr/HashMoonsTear.png', 'HashMoonsTear'),
    ('ITEM_TOWN_DEED', 'mmr/HashLandDeed.png', 'HashLandDeed'),
    ('ITEM_ROOM_KEY', 'mmr/HashRoomKey.png', 'HashRoomKey'),
    ('ITEM_MAMA_LETTER', 'mmr/HashMamaLetter.png', 'HashMamaLetter'),
    ('ITEM_KAFEI_LETTER', 'mmr/HashKafeiLetter.png', 'HashKafeiLetter'),
    ('ITEM_PENDANT', 'mmr/HashPendant.png', 'HashPendant'),
    ('ITEM_MAP', 'mmr/HashMap.png', 'HashMap'),
    ('ITEM_DEKU_MASK', 'mmr/HashDekuMask.png', 'HashDekuMask'),
    ('ITEM_GORON_MASK', 'mmr/HashGoronMask.png', 'HashGoronMask'),
    ('ITEM_ZORA_MASK', 'mmr/HashZoraMask.png', 'HashZoraMask'),
    ('ITEM_FIERCE_DEITY_MASK', 'mmr/HashFierceDeity.png', 'HashFierceDeity'),
    ('ITEM_MASK_OF_TRUTH', 'mmr/HashMaskOfTruth.png', 'HashMaskOfTruth'),
    ('ITEM_KAFEI_MASK', 'mmr/HashKafeiMask.png', 'HashKafeiMask'),
    ('ITEM_ALL_NIGHT_MASK', 'mmr/HashAllNightMask.png', 'HashAllNightMask'),
    ('ITEM_BUNNY_HOOD', 'mmr/HashBunnyHood.png', 'HashBunnyHood'),
    ('ITEM_KEATON_MASK', 'mmr/HashKeatonMask.png', 'HashKeatonMask'),
    ('ITEM_GARO_MASK', 'mmr/HashGaroMask.png', 'HashGaroMask'),
    ('ITEM_ROMANI_MASK', 'mmr/HashRomaniMask.png', 'HashRomaniMask'),
    ('ITEM_CIRCUS_LEADER_MASK', 'mmr/HashCircusLeader.png', 'HashCircusLeader'),
    ('ITEM_POSTMAN_HAT', 'mmr/HashPostmansHat.png', 'HashPostmansHat'),
    ('ITEM_COUPLE_MASK', 'mmr/HashCouplesMask.png', 'HashCouplesMask'),
    ('ITEM_FAIRY_SWORD', 'mmr/HashGFS.png', 'HashGFS'),
    ('ITEM_GIBDO_MASK', 'mmr/HashGibdoMask.png', 'HashGibdoMask'),
    ('ITEM_DON_GERO_MASK', 'mmr/HashDonGeroMask.png', 'HashDonGeroMask'),
    ('ITEM_KAMARO_MASK', 'mmr/HashKamaroMask.png', 'HashKamaroMask'),
    ('ITEM_CAPTAIN_HAT', 'mmr/HashCaptainsHat.png', 'HashCaptainsHat'),
    ('ITEM_STONE_MASK', 'mmr/HashStoneMask.png', 'HashStoneMask'),
    ('ITEM_BREMEN_MASK', 'mmr/HashBremenMask.png', 'HashBremenMask'),
    ('ITEM_BLAST_MASK', 'mmr/HashBlastMask.png', 'HashBlastMask'),
    ('ITEM_MASK_OF_SCENTS', 'mmr/HashMaskOfScents.png', 'HashMaskOfScents'),
    ('ITEM_GIANT_MASK', 'mmr/HashGiantsMask.png', 'HashGiantsMask'),
    ('ITEM_KOKIRI_SWORD', 'mmr/HashKokiriSword.png', 'HashKokiriSword'),
    ('ITEM_GILDED_SWORD', 'mmr/HashGildedSword.png', 'HashGildedSword'),
    ('ITEM_HELIX_SWORD', 'mmr/HashHelixSword.png', 'HashHelixSword'),
    ('ITEM_HERO_SHIELD', 'mmr/HashHeroShield.png', 'HashHeroShield'),
    ('ITEM_MIRROR_SHIELD', 'mmr/HashMirrorShield.png', 'HashMirrorShield'),
    ('ITEM_QUIVER_40', 'mmr/HashQuiver.png', 'HashQuiver'),
    ('ITEM_ADULT_WALLET', 'mmr/HashAdultWallet.png', 'HashAdultWallet'),
    ('ITEM_BOMBERS_NOTEBOOK', 'mmr/HashBombersNote.png', 'HashBombersNote'),
    ('0x61', 'mmr/HashBombersNote.png', 'HashBombersNote')
) AS icons(name, file_name, racetime_emoji)
WHERE games.name = 'mmr'
ON CONFLICT (game_id, name) DO UPDATE SET file_name=EXCLUDED.file_name,
    racetime_emoji=EXCLUDED.racetime_emoji;
