//! Short-lived, public practice results. No database persistence is needed.
use {
    super::{PracticeSeedForm, PracticeSeedStatus},
    crate::prelude::*,
    crate::racetime_bot::seed_gen_type::{AlttprDrSource, PracticeOption, SeedGenType},
};

pub(crate) const RETENTION: Duration = Duration::from_secs(24 * 60 * 60);
pub(super) const RETENTION_NOTICE: &str = "Practice result links can be reopened and shared for 24 hours after requesting a seed, or until HTH restarts, whichever comes first.";

#[derive(Default)]
pub(crate) struct PracticeSeedStore {
    jobs: HashMap<Uuid, Job>,
}

#[derive(Clone)]
pub(super) struct Job {
    series: Series,
    event: String,
    expires_at: Instant,
    pub(super) status: PracticeSeedStatus,
    generated_by: String,
    requested_at: DateTime<Utc>,
    generated_at: Option<DateTime<Utc>>,
    expires_at_utc: DateTime<Utc>,
}

pub(crate) type PracticeSeeds = Arc<tokio::sync::RwLock<PracticeSeedStore>>;

impl PracticeSeedStore {
    pub(super) async fn start(
        seeds: &PracticeSeeds,
        series: Series,
        event: &str,
        generated_by: Option<String>,
    ) -> Uuid {
        let id = Uuid::new_v4();
        let requested_at = Utc::now();
        let expires_at = Instant::now() + RETENTION;
        seeds.write().await.jobs.insert(
            id,
            Job {
                series,
                event: event.to_owned(),
                expires_at,
                status: PracticeSeedStatus::Generating,
                generated_by: generated_by.unwrap_or_else(|| "Anonymous".into()),
                requested_at,
                generated_at: None,
                expires_at_utc: requested_at
                    + TimeDelta::from_std(RETENTION).expect("practice retention fits chrono"),
            },
        );
        let seeds = Arc::clone(seeds);
        tokio::spawn(async move {
            sleep_until(expires_at).await;
            seeds.write().await.jobs.remove(&id);
        });
        id
    }

    pub(crate) fn finish(&mut self, id: Uuid, status: PracticeSeedStatus) {
        // A late generator response must never resurrect an expired result.
        if let Some(job) = self
            .jobs
            .get_mut(&id)
            .filter(|job| Instant::now() < job.expires_at)
        {
            if matches!(status, PracticeSeedStatus::Done(_)) && job.generated_at.is_none() {
                job.generated_at = Some(Utc::now());
            }
            job.status = status;
        }
    }

    pub(super) fn get(&self, id: Uuid, series: Series, event: &str) -> Option<Job> {
        self.jobs
            .get(&id)
            .filter(|job| {
                job.series == series && job.event == event && Instant::now() < job.expires_at
            })
            .cloned()
    }
}

impl Job {
    pub(super) fn details(&self, link: &str) -> RawHtml<String> {
        html! {
            dl {
                dt : "Generated by";
                dd { bdi : &self.generated_by; }
                dt : "Requested at";
                dd : format_datetime(self.requested_at, DateTimeFormat { long: true, running_text: false });
                dt : "Generated at";
                dd {
                    @if let Some(generated_at) = self.generated_at {
                        : format_datetime(generated_at, DateTimeFormat { long: true, running_text: false });
                    } else if matches!(self.status, PracticeSeedStatus::Generating) {
                        : "Generating…";
                    } else {
                        : "Not generated";
                    }
                }
                dt : "Expires at";
                dd {
                    : format_datetime(self.expires_at_utc, DateTimeFormat { long: true, running_text: false });
                    : " (or earlier if HTH restarts)";
                }
            }
            p : RETENTION_NOTICE;
            p {
                label(for = "practice-seed-link") : "Practice seed link";
                input(id = "practice-seed-link", type = "text", readonly, value = link);
                button(id = "copy-practice-seed-link", type = "button") : "Copy link";
            }
            p(id = "practice-seed-copy-status", role = "status", aria_live = "polite");
            script(src = static_url!("practice-seed.js")) {}
        }
    }
}

pub(super) fn avianart_presets(generator: &SeedGenType) -> Vec<PracticeOption> {
    let SeedGenType::AlttprAvianart {
        default_preset,
        practice_presets,
    } = generator
    else {
        return vec![];
    };
    if !practice_presets.is_empty() {
        return practice_presets.clone();
    }
    default_preset
        .iter()
        .map(|preset| PracticeOption {
            value: preset.clone(),
            label: preset.clone(),
        })
        .collect()
}

/// Only accept options offered by this event's practice form.
pub(super) fn validate_form(
    generator: &SeedGenType,
    form: &mut PracticeSeedForm,
) -> Result<(), Status> {
    let allowed_choices: Vec<String> = match generator {
        SeedGenType::Owr { config, .. } => racetime_bot::owr_choice_keys(config),
        SeedGenType::AlttprDoorRando {
            practice_choices, ..
        } => practice_choices
            .iter()
            .map(|option| option.value.clone())
            .collect(),
        _ => vec![],
    };
    if form
        .choices
        .iter()
        .any(|choice| !allowed_choices.contains(choice))
    {
        return Err(Status::UnprocessableEntity);
    }
    match generator {
        SeedGenType::AlttprAvianart { .. } => {
            let presets = avianart_presets(generator);
            if presets.is_empty() {
                return Err(Status::NotFound);
            }
            if form.preset.as_deref().is_none_or(str::is_empty) && presets.len() == 1 {
                form.preset = Some(presets[0].value.clone());
            }
            if !presets
                .iter()
                .any(|preset| Some(preset.value.as_str()) == form.preset.as_deref())
            {
                return Err(Status::UnprocessableEntity);
            }
        }
        SeedGenType::AlttprDoorRando {
            source: AlttprDrSource::Boothisman,
            practice_modes,
            ..
        } => {
            if practice_modes.is_empty() {
                return Err(Status::NotFound);
            }
            if !practice_modes
                .iter()
                .any(|mode| Some(mode.value.as_str()) == form.mode.as_deref())
            {
                return Err(Status::UnprocessableEntity);
            }
        }
        SeedGenType::Owr { .. }
        | SeedGenType::OoTR
        | SeedGenType::TWWR { .. }
        | SeedGenType::AlttprDoorRando {
            source: AlttprDrSource::MutualChoices { .. },
            ..
        } => {}
        _ => return Err(Status::NotFound),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn form() -> PracticeSeedForm {
        PracticeSeedForm {
            csrf: String::new(),
            mode: None,
            preset: None,
            baseline: None,
            choices: vec![],
        }
    }

    #[tokio::test]
    async fn results_can_be_revisited_and_are_scoped_to_the_event() {
        let seeds = Arc::default();
        let series = all::<Series>().next().unwrap();
        let id = PracticeSeedStore::start(&seeds, series, "practice", None).await;
        assert!(matches!(
            seeds.read().await.get(id, series, "practice"),
            Some(Job {
                status: PracticeSeedStatus::Generating,
                ..
            })
        ));
        let requested = seeds.read().await.get(id, series, "practice").unwrap();
        assert!(requested.generated_at.is_none());
        assert_eq!(requested.generated_by, "Anonymous");
        assert_eq!(
            requested.expires_at_utc - requested.requested_at,
            TimeDelta::hours(24)
        );
        seeds.write().await.finish(
            id,
            PracticeSeedStatus::Done(super::super::PracticeSeedResult::Permalink {
                permalink: "seed".into(),
                seed_hash: "hash".into(),
            }),
        );
        let completed = seeds.read().await.get(id, series, "practice").unwrap();
        assert!(completed.generated_at.unwrap() >= requested.requested_at);
        assert_eq!(completed.expires_at_utc, requested.expires_at_utc);
        for _ in 0..2 {
            let reopened = seeds.read().await.get(id, series, "practice").unwrap();
            assert_eq!(reopened.generated_at, completed.generated_at);
            assert_eq!(reopened.expires_at_utc, completed.expires_at_utc);
            assert!(matches!(
                seeds.read().await.get(id, series, "practice"),
                Some(Job {
                    status: PracticeSeedStatus::Done(_),
                    ..
                })
            ));
        }
        assert!(seeds.read().await.get(id, series, "other").is_none());
        let other_series = all::<Series>().find(|other| *other != series).unwrap();
        assert!(
            seeds
                .read()
                .await
                .get(id, other_series, "practice")
                .is_none()
        );
        assert!(
            PracticeSeedStore::default()
                .get(id, series, "practice")
                .is_none()
        );
    }

    #[tokio::test]
    async fn expired_jobs_cannot_be_read_or_resurrected() {
        let seeds = Arc::default();
        let series = all::<Series>().next().unwrap();
        let id = PracticeSeedStore::start(&seeds, series, "practice", None).await;
        let mut store = seeds.write().await;
        assert!(store.jobs[&id].expires_at <= Instant::now() + RETENTION);
        store.jobs.get_mut(&id).unwrap().expires_at = Instant::now();
        store.finish(id, PracticeSeedStatus::Error("late result".into()));
        assert!(store.get(id, series, "practice").is_none());
        assert!(matches!(
            store.jobs[&id].status,
            PracticeSeedStatus::Generating
        ));
        store.jobs.remove(&id);
        store.finish(id, PracticeSeedStatus::Error("late result".into()));
        assert!(store.jobs.is_empty());
    }

    #[test]
    fn avianart_default_preset_works_without_a_practice_list() {
        let generator = SeedGenType::from_db(
            Some("alttpr_avianart"),
            Some(&json!({"preset": "casualboots"})),
        )
        .unwrap();
        assert_eq!(avianart_presets(&generator)[0].value, "casualboots");
        let mut form = form();
        validate_form(&generator, &mut form).unwrap();
        assert_eq!(form.preset.as_deref(), Some("casualboots"));
        form.preset = Some("unconfigured".into());
        assert_eq!(
            validate_form(&generator, &mut form),
            Err(Status::UnprocessableEntity)
        );
    }

    #[test]
    fn avianart_practice_list_limits_selection() {
        let generator = SeedGenType::from_db(Some("alttpr_avianart"), Some(&json!({"preset": "default", "practice_presets": [{"value": "open", "label": "Open"}, {"value": "casualboots", "label": "Casual Boots"}]}))).unwrap();
        let mut form = form();
        assert_eq!(
            validate_form(&generator, &mut form),
            Err(Status::UnprocessableEntity)
        );
        form.preset = Some("default".into());
        assert_eq!(
            validate_form(&generator, &mut form),
            Err(Status::UnprocessableEntity)
        );
        form.preset = Some("open".into());
        validate_form(&generator, &mut form).unwrap();
        let generator = SeedGenType::from_db(Some("alttpr_avianart"), Some(&json!({}))).unwrap();
        assert!(avianart_presets(&generator).is_empty());
        assert_eq!(validate_form(&generator, &mut form), Err(Status::NotFound));
    }

    #[test]
    fn both_owr_builds_accept_configured_choices() {
        for (name, build) in [
            ("owr", racetime_bot::seed_gen_type::OwrBuild::Regular),
            (
                "owr_tourney",
                racetime_bot::seed_gen_type::OwrBuild::Tournament,
            ),
        ] {
            let generator = SeedGenType::from_db(Some(name), Some(&json!({"base_settings": {}, "choices": {"pots": {"label": "Pots", "settings": {"pot_shuffle": true}}}}))).unwrap();
            assert!(
                matches!(&generator, SeedGenType::Owr { build: actual, .. } if *actual == build)
            );
            let mut form = form();
            form.choices = vec!["pots".into()];
            validate_form(&generator, &mut form).unwrap();
            form.choices.push("unconfigured".into());
            assert_eq!(
                validate_form(&generator, &mut form),
                Err(Status::UnprocessableEntity)
            );
        }
    }

    #[tokio::test]
    #[ignore = "requires HTH_TEST_DATABASE_URL"]
    async fn public_practice_pages_and_background_results_can_be_revisited() {
        use rocket::local::asynchronous::Client;
        let pool = super::super::configuration::test_pool().await;
        let event = format!("p{:07x}", rng().random_range(0_u32..0x10000000));
        let seeds: PracticeSeeds = Arc::default();
        let result = std::panic::AssertUnwindSafe(async {
            sqlx::query("INSERT INTO events (series, event, display_name, team_config) VALUES ('xkeys', $1, 'Practice route test', 'solo')")
                .bind(&event).execute(&pool).await.unwrap();
            let rocket = rocket::build().manage(pool.clone()).manage(Arc::clone(&seeds))
                .attach(rocket_csrf::Fairing::default())
                .mount("/", rocket::routes![super::super::practice_seed, super::super::practice_seed_status]);
            let client = Client::tracked(rocket).await.unwrap();
            let path = format!("/event/xkeys/{event}/practice");
            for (generator, config, expected) in [
                ("alttpr_avianart", json!({"preset": "casualboots"}), "casualboots"),
                ("owr", json!({"base_settings": {}, "choices": {"pots": {"label": "Pottery", "settings": {"pot_shuffle": true}}}}), "Pottery"),
                ("owr_tourney", json!({"baselines": {"open": {"label": "Open mode", "base_settings": {}}}}), "Open mode"),
            ] {
                sqlx::query("UPDATE events SET seed_gen_type = $1, seed_config = $2 WHERE series = 'xkeys' AND event = $3")
                    .bind(generator).bind(config).bind(&event).execute(&pool).await.unwrap();
                let response = client.get(&path).dispatch().await;
                assert_eq!(response.status(), Status::Ok);
                let html = response.into_string().await.unwrap();
                assert!(html.contains(expected), "{html}");
                assert!(html.contains("Generate Practice Seed") && html.contains("24 hours"));
            }
            let hash = ["Bomb", "Powder", "Rod", "Ocarina", "BugNet"].map(str::to_owned);
            for files in [
                seed::Files::AvianartSeed { hash: "practice-test".into(), seed_hash: Some(hash.clone()) },
                seed::Files::AlttprDoorRando { uuid: Uuid::new_v4(), is_owr: true },
            ] {
                let id = PracticeSeedStore::start(&seeds, Series::Crosskeys, &event, match &files { seed::Files::AvianartSeed { .. } => None, _ => Some("Seed Roller <test>".into()) }).await;
                let result_path = format!("{path}/{id}");
                let response = client.get(&result_path).dispatch().await;
                assert_eq!(response.status(), Status::Ok);
                assert!(response.into_string().await.unwrap().contains("Generating Practice Seed"));
                let (tx, rx) = mpsc::channel(1);
                racetime_bot::start_practice_seed_roll(Arc::clone(&seeds), id, rx, vec![]);
                tx.send(racetime_bot::SeedRollUpdate::Done {
                    seed: seed::Data { file_hash: Some(hash.clone()), password: None, seed_data: Some(files.to_seed_data_base()), progression_spoiler: false },
                    rsl_preset: None, version: None, unlock_spoiler_log: UnlockSpoilerLog::Never, resolved_randoms: None,
                }).await.unwrap();
                tokio::time::timeout(Duration::from_secs(5), async {
                    loop {
                        if matches!(seeds.read().await.get(id, Series::Crosskeys, &event), Some(Job { status: PracticeSeedStatus::Done(_), .. })) { break; }
                        tokio::task::yield_now().await;
                    }
                }).await.unwrap();
                for _ in 0..2 {
                    let response = client.get(&result_path).dispatch().await;
                    assert_eq!(response.status(), Status::Ok);
                    let html = response.into_string().await.unwrap();
                    assert!(html.contains("Practice Seed Ready"));
                    assert_eq!(html.matches("class=\"hash-icon\"").count(), 5);
                    for (name, file) in hash.iter().zip(["HashBombs.png", "HashMagicPowder.png", "HashIceRod.png", "HashFlute.png", "HashBugnet.png"]) {
                        assert!(html.contains(&format!("alt=\"{name}\"")));
                        assert!(html.contains(&format!("/static/hash-icon/{file}")));
                    }
                    assert!(html.contains("24 hours") && html.contains("Generate another seed"));
                    let job = seeds.read().await.get(id, Series::Crosskeys, &event).unwrap();
                    for timestamp in [job.requested_at, job.generated_at.unwrap(), job.expires_at_utc] {
                        assert!(html.contains(&timestamp.timestamp_millis().to_string()));
                    }
                    assert!(html.contains("Generated by") && html.contains("Generated at") && html.contains("Expires at"));
                    assert!(html.contains("Copy link") && html.contains("practice-seed.js") && html.contains(&result_path));
                    if let Ok(path) = std::env::var("HTH_PRACTICE_PAGE_FIXTURE") {
                        std::fs::write(path, &html).unwrap();
                    }
                    match &files {
                        seed::Files::AvianartSeed { .. } => assert!(html.contains("https://avianart.games/perm/practice-test") && html.contains("Anonymous")),
                        _ => assert!(html.contains("Open in Patcher") && html.contains("OR_") && html.contains("Seed Roller &lt;test&gt;")),
                    }
                }
                assert_eq!(client.get(format!("/event/xkeys/other/practice/{id}")).dispatch().await.status(), Status::NotFound);
                seeds.write().await.jobs.get_mut(&id).unwrap().expires_at = Instant::now();
                assert_eq!(client.get(&result_path).dispatch().await.status(), Status::NotFound);
            }
        }).catch_unwind().await;
        sqlx::query("DELETE FROM events WHERE series = 'xkeys' AND event = $1")
            .bind(&event)
            .execute(&pool)
            .await
            .unwrap();
        if let Err(error) = result {
            std::panic::resume_unwind(error);
        }
    }
}
